baseURL = 'http://localhost:1313/'
languageCode = 'en-US'
title = 'Demo'
theme = 'PaperMod'
defaultContentLanguage = "cn"
defaultContentLanguageInSubdir = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[languages]
  [languages.en]
    languageCode = "en-US"
    languageName = "English"
    contentDir = "content/en"
    weight = 3
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = 'Categories'
        pageRef = '/categories'
        weight = 10
      [[languages.en.menu.main]]
        name = 'Tags'
        pageRef = '/tags'
        weight = 20
      [[languages.en.menu.main]]
        name = 'Archives'
        pageRef = '/archives'
        weight = 30
      [[languages.en.menu.main]]
        name = 'Library'
        pageRef = '/library'
        weight = 40
      [[languages.en.menu.main]]
        name = 'Explore'
        pageRef = '/explore'
        weight = 50

  [languages.ja]
    languageCode = "ja-JP"
    languageName = "æ—¥æœ¬èª"
    contentDir = "content/ja"
    weight = 2
    [languages.ja.menu]
      [[languages.ja.menu.main]]
        name = 'ã‚«ãƒ†ã‚´ãƒª'
        pageRef = '/categories'
        weight = 10
      [[languages.ja.menu.main]]
        name = 'ã‚¿ã‚°'
        pageRef = '/tags'
        weight = 20
      [[languages.ja.menu.main]]
        name = 'ã‚¢ãƒ¼ã‚«ã‚¤ãƒ–'
        pageRef = '/archives'
        weight = 30
      [[languages.ja.menu.main]]
        name = 'ãƒ©ã‚¤ãƒ–ãƒ©ãƒª'
        pageRef = '/library'
        weight = 40
      [[languages.ja.menu.main]]
        name = 'ã‚¨ã‚¯ã‚¹ãƒ—ãƒ­ãƒ¼ãƒ©'
        pageRef = '/explore'
        weight = 50

  [languages.cn]
    languageCode = "zh-CN"
    languageName = "ç®€ä½“ä¸­æ–‡"
    contentDir = "content/cn"
    weight = 1
    [languages.cn.menu]
      [[languages.cn.menu.main]]
        name = 'åˆ†ç±»'
        pageRef = '/categories'
        weight = 10
      [[languages.cn.menu.main]]
        name = 'æ ‡ç­¾'
        pageRef = '/tags'
        weight = 20
      [[languages.cn.menu.main]]
        name = 'æ—¶é—´è½´'
        pageRef = 'archives'
        weight = 30
      [[languages.cn.menu.main]]
        name = 'èµ„æ–™åº“'
        pageRef = '/library'
        weight = 40
      [[languages.cn.menu.main]]
        name = 'æ¢ç´¢å‘ç°'
        pageRef = '/explore'
        weight = 50

[params]
  [params.homeInfoParams]
    Title = "Hi there ğŸ‘‹"
    Content = "Can be Info, links, about..."
  [[params.socialIcons]]
    name = "youtube"
    url = "<link>"
  [[params.socialIcons]]
    name = "twitter"
    url = "<link>"
  [[params.socialIcons]]
    name = "github"
    url = "<link>"