baseURL = 'https://www.deux.top/'
title = '二重奏'
theme = 'PaperMod'
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true

hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true
enableRobotsTXT = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[languages]
  [languages.zh]
    languageCode = "zh-CN"
    languageName = "简体中文"
    contentDir = "content/zh"
    weight = 1

    [languages.zh.params.profileMode]
      enabled = true
      title = "精神与思想的二重奏"
      subtitle = "自由与独立的交响曲"
      imageUrl = "images/logo.jpg"
      imageWidth = 120
      imageHeight = 120

    [[languages.zh.params.profileMode.buttons]]
      name = "时间轴"
      url = "/zh/archives"
    [[languages.zh.params.profileMode.buttons]]
      name = "Github"
      url = "https://github.com/"
    [[languages.zh.params.socialIcons]]
      name = "youtube"
      url = "https://youtube.com/"
    [[languages.zh.params.socialIcons]]
      name = "twitter"
      url = "https://twitter.com/"
    [[languages.zh.params.socialIcons]]
      name = "github"
      url = "https://github.com/"

    [[languages.zh.menu.main]]
      identifier = "categories"
      name = '分类'
      pageRef = '/categories'
      weight = 10
    [[languages.zh.menu.main]]
      identifier = "tags"
      name = '标签'
      pageRef = '/tags'
      weight = 20
    [[languages.zh.menu.main]]
      identifier = "archives"
      name = '时间轴'
      pageRef = '/archives'
      weight = 30
    [[languages.zh.menu.main]]
      identifier = "library"
      name = '资料库'
      pageRef = '/library'
      weight = 40
    [[languages.zh.menu.main]]
      identifier = "explore"
      name = '探索发现'
      pageRef = '/explore'
      weight = 50

  [languages.ja]
    languageCode = "ja-JP"
    languageName = "日本語"
    contentDir = "content/ja"
    weight = 2

    [languages.ja.params.profileMode]
      enabled = true
      title = "精神と思考の二重奏"
      subtitle = "自由と独立の交響曲"
      imageUrl = "images/logo.jpg"
      imageWidth = 120
      imageHeight = 120

    [[languages.ja.menu.main]]
      identifier = "categories"
      name = 'カテゴリ'
      pageRef = '/categories'
      weight = 10
    [[languages.ja.menu.main]]
      identifier = "tags"
      name = 'タグ'
      pageRef = '/tags'
      weight = 20
    [[languages.ja.menu.main]]
      identifier = "archives"
      name = 'アーカイブ'
      pageRef = '/archives'
      weight = 30
    [[languages.ja.menu.main]]
      identifier = "library"
      name = 'ライブラリ'
      pageRef = '/library'
      weight = 40
    [[languages.ja.menu.main]]
      identifier = "explore"
      name = 'エクスプローラ'
      pageRef = '/explore'
      weight = 50

  [languages.en]
    languageCode = "en-US"
    languageName = "English"
    contentDir = "content/en"
    weight = 3

    [languages.en.params.profileMode]
      enabled = true
      title = "A duet of spirit and thought"
      subtitle = "a symphony of freedom and independence"
      imageUrl = "images/logo.jpg"
      imageWidth = 120
      imageHeight = 120

    [[languages.en.menu.main]]
      identifier = "categories"
      name = 'Categories'
      pageRef = '/categories'
      weight = 10
    [[languages.en.menu.main]]
      identifier = "tags"
      name = 'Tags'
      pageRef = '/tags'
      weight = 20
    [[languages.en.menu.main]]
      identifier = "archives"
      name = 'Archives'
      pageRef = '/archives'
      weight = 30
    [[languages.en.menu.main]]
      identifier = "library"
      name = 'Library'
      pageRef = '/library'
      weight = 40
    [[languages.en.menu.main]]
      identifier = "explore"
      name = 'Explore'
      pageRef = '/explore'
      weight = 50
